"""renamed missing_keyword to missing_keywords

Revision ID: 08baac8aa05f
Revises: 59fbcfeefea6
Create Date: 2026-05-26 15:17:12.479879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '08baac8aa05f'
down_revision = '59fbcfeefea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missing_keywords', sa.JSON(), nullable=True))
        batch_op.drop_column('missing_keyword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missing_keyword', sqlite.JSON(), nullable=True))
        batch_op.drop_column('missing_keywords')

    # ### end Alembic commands ###
