"""add is_primary

Revision ID: 0e8a01e2872a
Revises: 6388e95982be
Create Date: 2026-05-25 13:23:12.448877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8a01e2872a'
down_revision = '6388e95982be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
