"""add jd and resume notes

Revision ID: 29160823b49b
Revises: 62ce69ea6ea4
Create Date: 2026-05-22 11:44:44.545285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29160823b49b'
down_revision = '62ce69ea6ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_descritpion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resume_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('resume_notes')
        batch_op.drop_column('job_descritpion')

    # ### end Alembic commands ###
