"""create tables

Revision ID: 3a95d0c3fdbc
Revises: 
Create Date: 2026-05-25 16:11:31.521657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a95d0c3fdbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('role_title', sa.String(length=150), nullable=False),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('work_mode', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', name='workmode'), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', name='employmenttype'), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'ASSESSMENT', 'INTERVIEW', 'OFFER', 'REJECTED', 'GHOSTED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='prioritylevel'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('date_saved', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_descritpion', sa.Text(), nullable=True),
    sa.Column('resume_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_user_id'), ['user_id'], unique=False)

    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_documents_job_application_id'), ['job_application_id'], unique=False)

    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_events_job_application_id'), ['job_application_id'], unique=False)

    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('keyword_match_score', sa.Integer(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('missing_keyword', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['application_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_analyses_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_job_application_id'), ['job_application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analyses_job_application_id'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_document_id'))

    op.drop_table('resume_analyses')
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_events_job_application_id'))

    op.drop_table('application_events')
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_documents_job_application_id'))

    op.drop_table('application_documents')
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_status'))

    op.drop_table('job_applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
