"""add application documents

Revision ID: 56f6fa115d86
Revises: 29160823b49b
Create Date: 2026-05-22 14:43:25.874601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f6fa115d86'
down_revision = '29160823b49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_documents_job_application_id'), ['job_application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_documents_job_application_id'))

    op.drop_table('application_documents')
    # ### end Alembic commands ###
