"""add weakness and ats observation and fixed typo in job_application

Revision ID: 59fbcfeefea6
Revises: 3a95d0c3fdbc
Create Date: 2026-05-26 15:16:24.427038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fbcfeefea6'
down_revision = '3a95d0c3fdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.Text(), nullable=True))
        batch_op.drop_column('job_descritpion')

    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ats_observations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weakness', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_column('weakness')
        batch_op.drop_column('ats_observations')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_descritpion', sa.TEXT(), nullable=True))
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###
