"""table reset

Revision ID: 635911cbf5e8
Revises: ea4813eac524
Create Date: 2026-05-29 14:44:34.673257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635911cbf5e8'
down_revision = 'ea4813eac524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_interview_questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_interview_questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
