"""added new columns

Revision ID: 6388e95982be
Revises: 56f6fa115d86
Create Date: 2026-05-25 12:37:18.077425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6388e95982be'
down_revision = '56f6fa115d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
