"""add interview_prep table

Revision ID: 65cfc9e15e55
Revises: 84dda95c401e
Create Date: 2026-05-28 13:32:12.378122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cfc9e15e55'
down_revision = '84dda95c401e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('prep_type', sa.String(length=50), nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=True),
    sa.Column('questions_json', sa.JSON(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['application_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_preps_job_application_id'), ['job_application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_preps_job_application_id'))

    op.drop_table('interview_preps')
    # ### end Alembic commands ###
