"""add DB tailoring fields

Revision ID: 84dda95c401e
Revises: a5b9cde4b9aa
Create Date: 2026-05-27 14:54:28.232950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dda95c401e'
down_revision = 'a5b9cde4b9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('improved_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bullet_improvements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recruiter_impression', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_column('recruiter_impression')
        batch_op.drop_column('bullet_improvements')
        batch_op.drop_column('improved_summary')

    # ### end Alembic commands ###
