"""added mock interview session table

Revision ID: 871e8bf0e992
Revises: 65cfc9e15e55
Create Date: 2026-05-29 13:43:06.022910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871e8bf0e992'
down_revision = '65cfc9e15e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
