"""added resume analysis versioning fields

Revision ID: a5b9cde4b9aa
Revises: 08baac8aa05f
Create Date: 2026-05-27 14:24:14.232237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b9cde4b9aa'
down_revision = '08baac8aa05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('analysis_type', sa.String(length=50), server_default='resume_review', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_column('analysis_type')
        batch_op.drop_column('is_latest')

    # ### end Alembic commands ###
